<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <svg height="100" width="100" >
        <?php echo genCircle(50,50,30);?>
    </svg> 
    <svg height="100" width="100" >
        
        <?php echo genRectangle(20,30,100,100,'black',1,'red',0.1);?>
    </svg> 
    <svg height="100" width="100">
    </svg> 
    <svg height="100" width="100" >
        <?php echo genElipse(100,100,30,20);?>
    </svg> 
    <svg height="100" width="100" >
        <?php echo genPolygone();?>
    </svg> 
    
    
</body>
</html>