<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>Titre numéro 1</h1> 
        <nav>
            <a href="#">Lien1</a>
            <a href="#">Lien2</a>
            <a href="#">Lien3</a>
        </nav>
    </header>
    <main>
        <div>
            <h2>Titre Contenu 1</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est sint reiciendis reprehenderit modi porro soluta dolore sit impedit iure, nemo officiis inventore cum voluptates ut nesciunt corporis deleniti vel necessitatibus!</p>
        </div>
        <div>
            <h2>Titre Contenu 2</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est sint reiciendis reprehenderit modi porro soluta dolore sit impedit iure, nemo officiis inventore cum voluptates ut nesciunt corporis deleniti vel necessitatibus!</p>
        </div>
        <div>
            <h2>Titre Contenu 3</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est sint reiciendis reprehenderit modi porro soluta dolore sit impedit iure, nemo officiis inventore cum voluptates ut nesciunt corporis deleniti vel necessitatibus!</p>
        </div>
    </main>
    
</body>
</html>