
<form action="<?=buildUrl('editModel',['model_id' =>$idMod]);?>" method="post" enctype="multipart/form-data">
    <fieldset>
    
        <legend>Modifier un model</legend>
        <div class="form-field">
            <label for="productName">Nom du produit</label>
            <input type="text" name="productName" id="productName" value="<?=$productName?>">
        </div>
        <div class="form-field">
            <label for="productPrice">Prix du produit </label>
            <input type="number" name="productPrice" id="productPrice" min="1" max="800" value="<?=$prix?>">
        </div>
        <div class="form-field">
            <label for="productDescription">Description du produit</label>
            <input type="text" name="productDescription" id="productDescription" value="<?=$desc?>">
        </div>
        <div>
                <label for="productThumbnail">Select image:</label>
                <input type="file" id="productThumbnail" name="productThumbnail" accept="image/*" value="<?=$imgPat?>">
                <label for="productThumbnailVig">Selectionnez les vignette de variations</label>
                
            </div> 
        <div class="form-field">
            <label for="productCategory">Catégorie</label>
            <select id="productCategory" name="productCategory" required>
                <?php foreach ($categories as $category): ?>
                    <?php $selected = isset($selectedCategory) && $category['idCategorie'] == $idCategorie ? 'selected' : ''; ?>
                    <option <?=$selected?> value="<?=$category['idCategorie'];?>"><?=$category['libCategorie'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-field">
            <label for="productBrand">Marque</label>
            <select id="productBrand" name="productBrand" required>
                <?php foreach ($brands as $brand): ?>
                    <option value="<?=$brand['idMarque'];?>"><?=$brand['libMarque'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <input type="submit" value="Modifer">
    </fieldset>
</form>