<form action="<?=buildUrl('editColor',['color_id' => $colorId]);?>" method="post">
    <fieldset>
        <legend>Modifer une Categorie</legend>
        <div class="form-field">
            <label for="colorName">Nom de la Catégorie</label>
            <input type="text" name="colorName" id="colorName" value='<?=$color?>'>
        </div>
        <input type="submit" value="Modifier">
    </fieldset>
</form>
