<form action="<?=buildUrl('editCategory',['category_id' => $categoryId]);?>" method="post">
    <fieldset>
        <legend>Modifer une Categorie</legend>
        <div class="form-field">
            <label for="categoryName">Nom de la Catégorie</label>
            <input type="text" name="categoryName" id="categoryName" value='<?=$cat['libCategorie']?>'>
        </div>
        <input type="submit" value="Modifer">
        
    </fieldset>
</form>


