
       <ul>
           <?php foreach ($articles as $article): ?>
               <li>
                   <h3 class ='titreCat' ><?=htmlspecialchars($article['title']);?></h3>
                   <p >Date de création : <?=(new DateTimeImmutable($article['created_at']))->format('d/m/Y');?></p>
                   
                   <div><?=htmlspecialchars(mb_substr($article['content'],0,150));?></div>

                   <a href="<?=buildUrl('article', ['id' => intval($article['idArticle'])]);?>">Lire la suite</a>

                   <a href="<?=buildUrl('category',['id' => intval($article['idCategorie'])])?>"><?= $article['libCategorie']?></a>
                   
                   
               </li>
           <?php endforeach; ?>
       </ul>


