

<form action="<?=buildUrl('login');?>" method="post" class="form-example">
 
  <div class="form-field">
    <label for="email">Enter your email: </label>
    <input type="email" name="email" id="email" value="" required>
  </div>
  <div class="form-field">
    <label for="password">Enter your password </label>
    <input type="password" name="password" id="password" >
  </div>
  <div class="form-button">
    <input type="submit" value="Connect">
  </div>
</form>

