<section class="NewCollection">
    
        <div class="wrapper">
            <ul class="items">
            <li class="item">0</li>
            <li class="item">1</li>
            <li class="item">2</li>
            <li class="item">3</li>
            <li class="item">4</li>
            <li class="item">5</li>
            <li class="item">6</li>
            <li class="item">7</li>
            <li class="item">8</li>
            <li class="item">9</li>
            </ul>
        </div>
   
</section>

<section class="HomeNav">
    <a class="HomeNav-link" id="Infosboutique" href="">Infos sur la boutique</a>
    <a class="HomeNav-link" id="Eshop" href="">E-shop</a>
    <a class="HomeNav-link" id="Promo" href="">Promotions</a>
</section>

<section class="ForYou">
    <h2 class="ForYou-title">Pourrait vous plaire</h2>
    <svg>Barre du dessous</svg>
    <div class="ForYou-Carroussel">
    <button type="button" class="slick-prev-fy">Previous</button>    
    <div class="slider-forYou">
    <?php if ($articles): ?>
          
    <?php endif; ?>
    </div>
    
</section>
