<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil du blog</title>
</head>
<body>
    <header>
        <h1>Bienvenue sur mon blog !!</h1>
        <nav>
            <!-- menu de navigation -->
        </nav>
    </header>
    <main>
        <h2>Les derniers articles</h2>
        
    </main>
</body>
</html>