<h2>Inscription</h2>
<!-- avec les variables dans value, on fait réapparaître ce qu'on a inséré s'il y a une erreur. -->
<form action="/signup" method="POST">
    <p>
        <label for="firstname"> Votre prénom : </label>
        <input type="text" name="firstname" id="firstname" value="<?=$firstname;?>">
        <br />
        <label for="lastname"> Votre nom : </label>
        <input type="text" name="lastname" id="lastname" value="<?=$lastname;?>">
        <br />
        <label for="email">Votre e-mail : </label>
        <input type="email" name="email" id="email" value="<?=$email;?>">
        <br />
        <label for="password">Votre mot de passe : </label>
        <input type="password" name="password" id="password">
        <br />
        <input type="submit" value="Valider" />
    </p>
</form>