<form action="<?=buildUrl('addCategory');?>" method="post">
    <fieldset>
        <legend>Ajouter une Categorie</legend>
        <div class="Form-field">
            <label for="categoryName" class="Form-field-lib">Nom de la Catégorie</label>
            <input type="text" name="categoryName" id="categoryName" class="Form-field-input">
        </div>
        <input type="submit" value="Ajouter" class="Form-submit">
        
    </fieldset>
</form>