<form action="<?=buildUrl('addColor');?>" method="post">
    <fieldset>
        <legend>Ajouter Une Couleur</legend>
        <div class="Form-field">
            <label for="colorName" class="Form-field-lib">Nom de la Couleur</label>
            <input type="text" name="colorName" id="colorName" class="Form-field-input">
        </div>
        <input type="submit" value="Ajouter" class="Form-submit">
    </fieldset>
</form>
