<div class="Admin-listing-size">
    
        <table class="Admin-listing-size-table">
            <thead class="Admin-listing-size-head">
                <tr>
                    <td>Libélé de la taille</td>
                   
                </tr>
            </thead>
            <tbody class="Admin-listing-size-body">
                <?php foreach($sizes as $size):?>
                    <tr id='brand-<?php $size['idTaille']?>'>
                        <td><?= $size['libTaille']?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>

<form action="<?=buildUrl('addSize');?>" method="post">
    <fieldset class="Form-fieldset">
        <legend class="Form-field-lib">Ajouter une Taille</legend>
        <div class="Form-field">
            <label for="sizeName">Taille</label>
            <input type="text" name="sizeName" id="sizeName" class="Form-field-input">
        </div>
        <input type="submit" value="Ajouter" class="Form-submit">
    
    </fieldset>
</form>