<!-- Template spécifique à la page d'accueil -->
<h2>Les derniers articles</h2>
<?php foreach ($articles as $article): ?>
    <article>
        <h3><?= $article['title'];?></h3>
        <small><?= (new DateTimeImmutable($article['created_at']))->format('d/m/Y') ;?></small>
        <p><?= mb_substr($article['content'], 0, 150);?> [...]</p>
        <a href="/blog/article?id=<?=$article['id'];?>">Lire la suite</a>
    </article>
<?php endforeach; ?>
    