<?php

/**
 * Ici on est dans le fichier de template : on a tout le code HTML et quelques bouts de code PHP
 * On cherche à avoir le moins de code PHP possible ici. On peut avoir des boucles, des conditions, 
 * et principalement des echo pour intégrer des données dans le code HTML
 */

 ?>
 
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenue PHP</title>
</head>
<body>
    <header>
        <h1>Introduction à PHP !</h1>
    </header>
    <main>
        <p><?php echo $message; ?></p>

        <section>
            <h2>Transmission via l'URL dans un lien</h2>
            <a href="hello.php?firstname=Alfred&lastname=Dupont">Clique ici pour bonjour à Alfred Dupont!</a>
        </section>

        <section>
            <h2>Transmission via l'URL dans un formulaire</h2>
            <form action="hello.php" method="GET">
                <div>
                    <label for="lastname">Votre nom</label>
                    <input type="text" id="lastname" name="lastname">
                </div>
                <div>
                    <label for="firstname">Votre prénom</label>
                    <input type="text" id="firstname" name="firstname">
                </div>
                <input type="submit" value="Valider">
            </form>
        </section>

    </main>
</body>
</html>