$('body').append(
    $('<table></table>')
    .append(
        $('<tr></tr>')
        .attr('id','tr1')
        .append(
            $('<td></td>')
            .attr('id','tdeffacer')
            .append(
                $('<button></button>')
                .attr('id','beffacer')
                .html('Effacer')
            ),
            $('<td></td>')
            .attr('colspan', 3 )
            .append(
                $('<input>')
                .attr('placeholder','0')
                .attr('colspan', 3 )
                .html('placeholder')
            )   
        ),
        $('<tr></tr>')
        .attr('id','tr2')
        .append(
            $('<td></td>')
            .attr('id','tdpourc')
            .append(
                $('<button>')
                .attr('id','bpourc')
                .html('%')
            ),
            $('<td></td>')
            .attr('id','tdxcarre')
            .append(
                $('<button>')
                .attr('id','bxcarre')
                .html('x²')
            ),
            $('<td></td>')
            .attr('id','tdrcarre')
            .append(
                $('<button>')
                .attr('id','brcarre')
                .html('√')
            ),
            $('<td></td>')
            .attr('id','tddivi')
            .append(
                $('<button>')
                .attr('id','bdivi')
                .html('÷')
            )
        ),
        $('<tr></tr>')
        .attr('id','tr3')
        .append(
            $('<td></td>')
            .attr('id','tdsept')
            .append(
                $('<button>')
                .attr('id','bsept')
                .html('7')
            ),
            $('<td></td>')
            .attr('id','tdhuit')
            .append(
                $('<button>')
                .attr('id','bhuit')
                .html('8')
            ),
            $('<td>')
            .attr('id','tdneuf')
            .append(
                $('<button>')
                .attr('id','bneuf')
                .html('9')
            ),
            $('<td>')
            .attr('id','tdX')
            .append(
                $('<button>')
                .attr('id','bX')
                .html('X')
            )
        ),
        $('<tr></tr>')
        .attr('id','tr4')
        .append(
            $('<td>')
            .attr('id','tdquatre')
            .append(
                $('<button>')
                .attr('id','bquatre')
                .html('4')
            ),
            $('<td>')
            .attr('id','tdcinq')
            .append(
                $('<button>')
                .attr('id','bcinqr')
                .html('5')
            ),
            $('<td>')
            .attr('id','tdsix')
            .append(
                $('<button>')
                .attr('id','bsix')
                .html('6')
            ),
            $('<td>')
            .attr('id','tdsept')
            .append(
                $('<button>')
                .attr('id','bsept')
                .html('-')
            )
        ),
        $('<tr></tr>')
        .attr('id','tr5')
        .append(
            $('<td>')
            .attr('id','tdun')
            .append(
                $('<button>')
                .attr('id','bun')
                .html('1')
            ),
            $('<td>')
            .attr('id','tddeux')
            .append(
                $('<button>')
                .attr('id','bdeux')
                .html('2')
            ),
            $('<td>')
            .attr('id','tdtrois')
            .append(
                $('<button>')
                .attr('id','btrois')
                .html('3')
            ),
            $('<td>')
            .attr('id','tdplus')
            .append(
                $('<button>')
                .attr('id','plus')
                .html('+')
            )
        ),
        $('<tr></tr>')
        .attr('id','tr6')
        .append(
            $('<td>')
            .attr('id','tdplusetmoin')
            .append(
                $('<button>')
                .attr('id','bplusetmoin')
                .html('+/-')
            ),
            $('<td>')
            .attr('id','tdzero')
            .append(
                $('<button>')
                .attr('id','bzero')
                .html('0')
            ),
            $('<td>')
            .attr('id','tdvirgule')
            .append(
                $('<button>')
                .attr('id','bvirgule')
                .html(',')
            ),
            $('<td>')
            .attr('id','tdegal')
            .append(
                $('<button>')
                .attr('id','begal')
                .html('=')
            )

        )
    )
    
);