<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painter SVG POO</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <h1>Paniter SVG</h1>
    </header>
    <main>
        <svg width="1200" height="600" id="painter">
           <?=$svg;?>
        </svg>
    </main>
</body>
</html>