<article>
    <h2><?= $article['title'];?></h2>
    <small><?= (new DateTimeImmutable($article['created_at']))->format('d/m/Y') ;?></small>
    <p><?= $article['content'];?></p>
</article>

<form action="/add-comment" method="post">
    <input type="hidden" name="article-id" value="<?=$article['id'];?>">
    <fieldset>
        <legend>Ajouter un commentaire</legend>
        <div>
            <label for="content">Commentaire</label>
            <textarea required id="content" name="content"></textarea>
        </div>
        <input type="submit" value="Envoyer">
    </fieldset>
</form>

<?php if ($comments): ?>
    <ul>
        <?php foreach ($comments as $comment): ?>
            <li>
                <h3>Ajouté le <?=(new DateTimeImmutable($comment['created_at']))->format('d/m/Y');?></h3>
                <p><?=$comment['content'];?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

