<!-- Template spécifique à la page d'accueil -->
<h2>Les derniers articles</h2>
<?php foreach ($articles as $article): ?>
    <article>
        <h3><?=htmlspecialchars($article['title']);?></h3>
        <p>Date de création : <?=(new DateTimeImmutable($article['created_at']))->format('d/m/Y');?></p>
        <div><?=htmlspecialchars(mb_substr($article['content'],0,150));?></div>
        <a href="<?=buildUrl('article', ['id' => intval($article['id'])]);?>">Lire la suite</a>
    </article>
<?php endforeach; ?>
    