<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <a href="http://localhost/Workingclass/olivier/php/introduction/hello.php?firstname=Alfred&lastname=Dupont">Dire bonjour a Fredo</a>
    <form action=" hello.php" method ="GET">
        <div>
            <label for="lastname" >Votre nom</label>
            <input id="lastname" type="text" name ="lastname">
        </div>
        <div>
            <label for="firstname" >Votre nom</label>
            <input id="firstname" type="text" name ="firstname">
        </div>
        <input type= "submit" value="Valider">
        </form>
</body>
</html>