<?php use App\Framework\FlashBag;?>
<?php use App\Framework\UserSession;?>
<!doctype html>
<html lang="fr">
<head>
   <meta charset="UTF-8">
   <title>Blog - <?=$pageTitle;?></title>
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet"> 
   <link rel="stylesheet" href="<?=asset('css/style.css');?>">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" referrerpolicy="no-referrer" />
</head>
<body>
<header class = 'siteHeader'>
<h1 class ='siteHeaderTitle'>Blog du mich mich </h1>


    <nav class="navMenu">
        <a class ='navMenu-link' href="<?= buildUrl('homepage')?>">HOME</a>
        <?php if (UserSession::isAuthenticated()):?>
        
            <a class ='navMenu-link' href="<?= buildUrl('logout')?>">LOGOUT</a>
    
        <?php else :?>
            <a class ='navMenu-link' href="<?= buildUrl('signup')?>">SIGNUP</a>
            <a class ='navMenu-link' href="<?= buildUrl('login')?>">LOGIN</a>
        <?php endif; ?>
        <a class ='navMenu-link' href="<?= buildUrl('category')?>">CATEGORIE</a> 
        <a class ='navMenu-link' href="<?= buildUrl('article')?>">ARTICLE</a>
        <?php if (UserSession::hasRole('ADMIN','EDITOR')):?>
            <a href="/admin">Administration</a>
        <?php endif; ?>
    </nav>

</header>

<aside>
   <?php if (FlashBag::hasMessages('error')):?>
       <?php foreach (FlashBag::fetchMessages('error') as $error):?>
           <p class="error-message"><?=$error;?></p>
       <?php endforeach; ?>
   <?php endif; ?>

   <?php if (FlashBag::hasMessages('success')):?>
       <?php foreach (FlashBag::fetchMessages('success') as $message):?>
           <p class="success-message"><?=$message;?></p>
       <?php endforeach; ?>
   <?php endif; ?>
</aside>
<main>
   <?php include TEMPLATE_DIR . '/' . $template . '.phtml';?>
</main>

</body>
</html>


