

<form action="<?=buildUrl('signup');?>" method="post" class="form-example">
  <div class="form-field">
    <label for="firstname">Enter your firstname: </label>
    <input type="text" name="firstname" id="firstname" value="<?=$firstname;?>" required>
  </div>
  <div class="form-field">
    <label for="lastname">Enter your lastname: </label>
    <input type="text" name="lastname" id="lastname" value="<?=$lastname;?>" required>
  </div>
  <div class="form-field">
    <label for="email">Enter your email: </label>
    <input type="email" name="email" id="email" value="<?=$email;?>" required>
  </div>
  <div class="form-field">
    <label for="password">Enter your password </label>
    <input type="password" name="password" id="password" >
  </div>
  <div class="form-button">
    <input type="submit" value="Subscribe!">
  </div>
</form>
