<?php use App\Framework\UserSession;?>
<?php if (UserSession::hasRole('ADMIN','EDITOR')):?>

<section>
    <h2>Modifier un article </h2>

    <form action="<?=buildUrl('admin_article_edit', ['article_id' => $articleId]);?>" method="POST" enctype="multipart/form-data">
        <fieldset>
            <div>
                <label for="title">Titre</label>
                <input type="text" id="title" name="title" value="<?=$article['title']?>">
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea id="content" name="content"><?=$article['content']?></textarea>
            </div>
            <div>
                <label for="category">Catégorie</label>
                <select id="category" name="category">
                <?php foreach ($categories as $categorie):?>

                    <option value="<?=$categorie['idCategorie'];?>" selected ='<?=$libCat?>'><?=$categorie['libCategorie'];?></option>

                <?php endforeach;?>
                    
                </select>
            </div>
            <div>
                <input type="file" id="img" name="img" accept="image/*">
                <button type="submit">Ajouter</button>
            </div>
            
            
        </fieldset>
    </form>
</section>
<?php else : ?>
<?php header('Location: ' . buildUrl('homepage'));?>
<?php endif?>