<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php print $titre ?></title>
</head>
<body>
    <ul>
        <li><a href="/Workingclass/sylvain/Template/php/acceuil">Acceuil</a></li>
        <li><a href="/Workingclass/sylvain/Template/php/nos-produits">Nos Produits</a></li>
        <li><a href="/Workingclass/sylvain/Template/php/contact">Contact</a></li>
        
    </ul>
    <h1><?php print $titre ?></h1>
</body>
</html>