<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <svg height="1200" width="1300" >
        <?php echo genCircle(100,200,30);?>  
        <?php echo genRectangle(40,50,100,100,'black',1,'red',0.1);?>
        <?php echo genElipse(100,100,30,20);?>
        <?php echo genPolygone([100,103,130,140,150,160,140,180,500,750,780,890,940,1000,1080,1150],'red','black');?>
    </svg> 
    
    
</body>
</html>