<Section class="LayoutConnect">

    <div class="Connect">
        <svg>Logo Sunday</svg>
        <div class="Connect-form">
            <form action="<?=buildUrl('login');?>" method="POST" class="form-connection">

                <div class="Connect-form-field email ">
                    <label for="mail">Adresse mail</label>
                    <input type="email" name="email" id="email" required>
                </div>

                <div class="Connect-form-field mdp">
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" id="password">
                    <a href="">Mot de passe oublié</a>
                </div>

                <input type="submit" value="Connectez vous">
            </form>

        </div>
        <button><i>COnnect with gogole</i></button>
        <button><i>COnnect with fakebook</i></button>
    </div>
    <div class="SignIn">
        <p>Vous n'avez pas encore de compte ?</p>
        <button>
            <p>Creer un compte !</p>
        </button>
    </div>
</Section>