<form action="" method="post" class="form-example">
  <div class="form-example">
    <label for="firstname">Enter your firstname: </label>
    <input type="text" name="name" id="name" required>
  </div>
  <div class="form-example">
    <label for="lastname">Enter your lastname: </label>
    <input type="text" name="name" id="name" required>
  </div>
  <div class="form-example">
    <label for="email">Enter your email: </label>
    <input type="email" name="email" id="email" required>
  </div>
  <div class="form-example">
    <label for="password">Enter your password </label>
    <input type="password" name="email" id="email" required>
  </div>
  <div class="form-example">
    <input type="submit" value="Subscribe!">
  </div>
</form>
